info:
  name: get_item_request_so_doc (2)
  type: http
  seq: 6

http:
  method: GET
  url: http://{{host}}:{{port}}/api/engineering/bin_location/1
  auth: inherit

runtime:
  variables:
    - name: port
      value: "3000"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
